### ISSUE TITLE
Make node types optional

### ISSUE THREAD

**Issue by Razzile** [zajrik/discord.js-typings#13]
when using Visual Studio 2017, there is a clash of the declarations installed with this and visual studio's built in node definitions.

(an alternative solution would be to find a way to turn VS's built in definitions off)

![image](https://cloud.githubusercontent.com/assets/5256381/21534226/da09362a-cd5b-11e6-95ca-75219c3502c4.png)

**Comment by zajrik** [comment]
I don't actually use Visual Studio for TS development so I have no point of reference for this. However I don't actually see anything pertaining to these typings within that screenshot.

**Comment by Razzile** [comment]
Actually it turns out simply deleting the node declaration that is generated in a visual studio new project and relying on the one installed with this module is enough. I'll leave open in case anyone else has this problem

**Comment by zajrik** [comment]
Leaving an issue open for visibility when it's been resolved is a little silly so I'm going to go ahead and close it. I'm glad you were able to sort it out. I'll use this as a future point of reference, like you said, if anyone else has the problem.
