### ISSUE TITLE
DMChannel.send() return type wrong?

### ISSUE THREAD

**Issue by CorpulentBrony** [zajrik/discord.js-typings#15]
The return type for `DMChannel.send()` is `string` in index.d.ts, but according to the discord.js documentation this should be `Promise<Message | Message[]>` as it is for `GroupDMChannel` and `TextChannel`.

**Comment by zajrik** [comment]
This has already been fixed in current indev versions. If you install Discord.js from github you will receive the updated typings. `npm install --save hydrabolt/discord.js` 

Never was sure how this one got by me but it won't happen again with how I've restructured things going forward 👌
