### ISSUE TITLE
Guild.member may return undefined

### ISSUE THREAD

**Issue by Awpteamoose** [zajrik/discord.js-typings#17]
https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=member

The definition should be:
```typescript
member(user: UserResolvable): GuildMember | undefined;
```

Other methods which may return undefined are probably similarly mistyped.

**Comment by zajrik** [comment]
This is invalid. `undefined` and `null` are subtypes of all types. Anything and everything can have null or undefined compared to or assigned to it.

https://www.typescriptlang.org/docs/handbook/basic-types.html 

Scroll down to the `Null and Undefined` section for more information.

**Comment by Awpteamoose** [comment]
Yes, but --strictNullChecks won't catch it without an explicit definition.

**Comment by zajrik** [comment]
Accommodating strictNullChecks in typings is one: an exercise in frustration, and two: not common practice in module typings from what I have seen.

To my knowledge strictNullChecks prevents you from assigning null/undefined to variables declared as anything but null/undefined or from returning them in non-void functions that don't explicitly state it. This does not prevent you from making checks to verify that a returned value is actually null or undefined.

I could be wrong, I suppose but I personally have no intention of throwing `| null | undefined` union types onto every method return signature.

**Comment by arsdragonfly** [comment]
--strictNullChecks forces you to either explicitly handle a potential null value or get a compile-time type error (say you intended to return number, but you're actually returning number | undefined, which is an error). See here: https://www.typescriptlang.org/docs/handbook/advanced-types.html
