### ISSUE TITLE
Add 'How to use' section in readme

### ISSUE THREAD

**Issue by OiYouYeahYou** [zajrik/discord.js-typings#43]
Could you add a How to use section in the readme. This is the first time I've tried to use Typescriptand am coming a bit unstuck

**Comment by iCrawl** [comment]
There is no how to use. The moment you install discord.js it will install this typings package.

**Comment by zajrik** [comment]
Crawl is correct. When you `import { ... } from 'discord.js';` you are already utilizing the typings in that anything you import will be properly hinted to you via intellisense as a feature of your editor.

If, however, you are not using an editor that supports this out of the box, you will likely need to install some sort of add on that adds support for Typescript intellisense. I advise using VSCode for writing TypeScript as its native support for it is far greater than any other editor I've used for how lightweight it is overall.
