### ISSUE TITLE
package.json missing name

### ISSUE THREAD

**Issue by smotes** [zajrik/discord.js-typings#48]
I'm unable to install the v10.0.0 typings via npm due to the package.json file not having `name` property.

```
$ npm install --save git+https://github.com/zajrik/discord.js-typings.git#de59a23685c90429719111a4d5b7bd1cf57b2031
...
npm ERR! No name provided in package.json
...
```

**Comment by zajrik** [comment]
Regrettably I cannot retroactively fix this problem at a point in time that the typings were accurate for v10. This is not an npm package anyway, so this isn't particularly an issue I'm keen to address going forward either. The typings are included in discord.js automatically and will continue to be in the foreseeable future as long as I can continue get contributors. You should consider updating to at least discord.js 11.2.1

**Comment by ShayBox** [comment]
Just add the a name to the package.json 👀
