### ISSUE TITLE
Contribute to Definetely Typed

### ISSUE THREAD

**Issue by weeco** [zajrik/discord.js-typings#51]
Hey,
I was looking for type definitions for discord.js and I was surprised no has contributed types to Definetely Typed yet. Is there a reason you are maintaining them in your own Repo instead of contributing to DefinetelyTyped?

https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by zajrik** [comment]
We do not use DT because the typings have been a submodule of Discord.js since v10 or so. They are automatically available when Discord.js is installed from NPM. This is preferable to having to install them separately.

**Comment by weeco** [comment]
Oh I didn't even see the git submodule in the repo :D. I assume the submodule will be pulled before every new release?

**Comment by zajrik** [comment]
Correct. They are generally behind with regards to in-development stages of the library due to not being officially maintained alongside the library but we generally delay releases to ensure the typings are ready. Unless someone forgets about them, in which case they're patched in later.
