### ISSUE TITLE
discord.js 11.3.0 errors

### ISSUE THREAD

**Issue by ghost** [zajrik/discord.js-typings#54]
`node_modules/discord.js/typings/index.d.ts(60,23): error TS2304: Cannot find name 'Set'.
node_modules/discord.js/typings/index.d.ts(62,22): error TS2304: Cannot find name 'Set'.
node_modules/discord.js/typings/index.d.ts(267,40): error TS2304: Cannot find name 'Map'.
node_modules/discord.js/typings/index.d.ts(1182,20): error TS2304: Cannot find name 'Map'.
node_modules/discord.js/typings/index.d.ts(1333,23): error TS2304: Cannot find name 'Set'.
node_modules/discord.js/typings/index.d.ts(1334,22): error TS2304: Cannot find name 'Set'.
`

**Comment by zajrik** [comment]
Do you have `@types/node` installed?

**Comment by ghost** [comment]
@zajrik yes. I down graded discord.js to 11.2.0. This version works fine. But on 11.3.0 I have attached errors.

**Comment by SpaceEEC** [comment]
I can reproduce these warnings when running `tsc ./index.ts`
Running `tsc -t esnext -m commonjs ./index.ts` compiles fine however.

If this does not work / is applicable, telling us how you transpile your ts files would be helpful.
