### ISSUE TITLE
node_modules/discord.js/typings/index.d.ts(267,40): error TS2689: Cannot extend an interface 'Map'. Did you mean 'implements'?

### ISSUE THREAD

**Issue by mlagarrigue** [zajrik/discord.js-typings#57]
it happens when compiling my ts project
"discord.js@11.3.0",

you should just change
export class Collection<K, V> extends Map<K, V> {
into
export class Collection<K, V> implements Map<K, V> {
here is my tsconfig

```
{
    "compilerOptions": {
      /* Basic Options */
      "target": "ES5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', or 'ESNEXT'. */
      "module": "es2015",                         /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
      "sourceMap": true,                        /* Generates corresponding '.map' file. */
       "outDir": "./.build/",                    /* Redirect output structure to the directory. */

      /* Strict Type-Checking Options */
      "strict": true,                           /* Enable all strict type-checking options. */
       "noImplicitAny": true,                   /* Raise error on expressions and declarations with an implied 'any' type. */
       "strictNullChecks": true,                /* Enable strict null checks. */
       "strictFunctionTypes": true,             /* Enable strict checking of function types. */
       "noImplicitThis": true,                  /* Raise error on 'this' expressions with an implied 'any' type. */
       "alwaysStrict": true,                    /* Parse in strict mode and emit "use strict" for each source file. */
  
      /* Additional Checks */
       "noUnusedLocals": true,                  /* Report errors on unused locals. */
       "noUnusedParameters": true,              /* Report errors on unused parameters. */
       "noImplicitReturns": true,               /* Report error when not all code paths in function return a value. */
       "noFallthroughCasesInSwitch": true,       /* Report errors for fallthrough cases in switch statement. */
  
      /* Module Resolution Options */
       "moduleResolution": "node",            /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    }
  }
```

**Comment by zajrik** [comment]
Sorry, no. Collection legitimately extends map, it does not implement the interface. There is another issue present here, but I can't say for sure what it is. I can tell you, however, that I have no seen it before and Collection has ALWAYS extended Map in the typings without issue.

**Comment by zajrik** [comment]
What is your compilation target platform?

**Comment by mlagarrigue** [comment]
os windows 10 pro
tsc 2.6.2
node v8.9.1

**Comment by zajrik** [comment]
Consider changing your target in your tsconfig. That often has major effects on weird TS errors. ES5 is a little dated at this point. If you're not compiling for the web there's not to use the highest supported by your node version. Also, I'm not sure if your module setting would play a part in it as well but I don't believe es2015 is node compatible. Unless I haven't been keeping up with things 😥

**Comment by kyranet** [comment]
I found this issue with another user recently, but with the `Console` instead of `Map` (apparently in some builds, Console is an interface instead of a class). I assume the fix for that is the same as this one. Let us know if you get it fixed. 👍

**Comment by zajrik** [comment]
It could also simply be an issue with your installed @types/node version

**Comment by devsnek** [comment]
ES5 doesn't have `Map` so you can't target it

**Comment by zajrik** [comment]
Gus is correct. I hadn't considered that (and also didn't know it since I never used es5)

**Comment by mlagarrigue** [comment]
ok it works fine on  higher version of  scripting and by chance I don't have any regression 
it's ok for me but it could be great either to mention it on any readme.md (discord.js
or discord.js-typings) or to fix these kind of issue in the futur

thank you guys

**Comment by Gawdl3y** [comment]
no

**Comment by mlagarrigue** [comment]
> no

 no to what ? 
it's a too short answer.

at least it could be usefull to mention that it require higher than ES5 in a readme file 
isn't it ?
