### ISSUE TITLE
createMessageCollector() options should be MessageCollectorOptions instead of CollectorOptions

### ISSUE THREAD

**Issue by kevinzwang** [zajrik/discord.js-typings#70]
Line 1424 of [`index.d.ts`](https://github.com/discordjs/discord.js-typings/blob/master/index.d.ts#L1424).

In the [documentation](https://discord.js.org/#/docs/main/stable/class/GroupDMChannel?scrollTo=createMessageCollector), the type for createMessageCollector() is MessageCollectorOptions, which conflicts with the typings here.

**Comment by SpaceEEC** [comment]
Indeed a conflict. Thanks for spotting!
