### ISSUE TITLE
Make this a separate git repo

### ISSUE THREAD

**Issue by ghost** [zajrik/discord.js-typings#72]
Yarn or pnpm doesn't work with git submodules. So it would be nice to separate it out from the master and also publish it as @types/discord.js

**Comment by zajrik** [comment]
We have no plans to do this. Releases are published with the typings included. Until a time that yarn supports git submodules, npm will have to be used to install Discord.js master. It's not a big deal. I understand where you're coming from. I prefer yarn myself. But again, it's not a big deal.
